#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4d5a71aff70746648d516fdd25f6cbb0" }
]

[assets]
directory = "./public"
